
project_id = "xekxewtggioememydenu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
port = 54326

[analytics]
enabled = false

[functions.widget-webhook]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.whatsapp-check-status]
verify_jwt = true

[functions.whatsapp-create-session]
verify_jwt = true

[functions.whatsapp-disconnect]
verify_jwt = true

[functions.whatsapp-send-message]
verify_jwt = true
